[theme]
primaryColor="#1f1f1f"
backgroundColor="#f0f2f6"
secondaryBackgroundColor="#ffffff"
textColor="#1f1f1f"
font="sans serif"

[server]
enableXsrfProtection=true
enableCORS=false
enableWebsocketCompression=false

[browser]
gatherUsageStats=false 